/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomTokenObtainPair
 */
export interface CustomTokenObtainPair {
    /**
     * 
     * @type {string}
     * @memberof CustomTokenObtainPair
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CustomTokenObtainPair
     */
    'password': string;
}

