/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmergenciesType
 */
export interface EmergenciesType {
    /**
     * 
     * @type {number}
     * @memberof EmergenciesType
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof EmergenciesType
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof EmergenciesType
     */
    'icon': string;
}

