/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `pending` - Pending * `approved` - Approved * `rejected` - Rejected
 * @export
 * @enum {string}
 */

export const EmeregencyRoleSerializerResponseStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;

export type EmeregencyRoleSerializerResponseStatusEnum = typeof EmeregencyRoleSerializerResponseStatusEnum[keyof typeof EmeregencyRoleSerializerResponseStatusEnum];



