/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoleEnum } from './role-enum';

/**
 * 
 * @export
 * @interface EmergencyRoleSerializerRequest
 */
export interface EmergencyRoleSerializerRequest {
    /**
     * 
     * @type {RoleEnum}
     * @memberof EmergencyRoleSerializerRequest
     */
    'role': RoleEnum;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRoleSerializerRequest
     */
    'number_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRoleSerializerRequest
     */
    'adress'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRoleSerializerRequest
     */
    'plate_vehicle'?: string;
}



