/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmeregencyRoleSerializerResponseStatusEnum } from './emeregency-role-serializer-response-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { Role } from './role';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface EmeregencyRoleSerializerResponse
 */
export interface EmeregencyRoleSerializerResponse {
    /**
     * 
     * @type {number}
     * @memberof EmeregencyRoleSerializerResponse
     */
    'id': number;
    /**
     * 
     * @type {User}
     * @memberof EmeregencyRoleSerializerResponse
     */
    'user': User;
    /**
     * 
     * @type {EmeregencyRoleSerializerResponseStatusEnum}
     * @memberof EmeregencyRoleSerializerResponse
     */
    'status'?: EmeregencyRoleSerializerResponseStatusEnum;
    /**
     * 
     * @type {Role}
     * @memberof EmeregencyRoleSerializerResponse
     */
    'requested_role': Role;
    /**
     * 
     * @type {string}
     * @memberof EmeregencyRoleSerializerResponse
     */
    'plate_vehicle': string;
}



