/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `ciudadano` - ciudadano * `policia` - policia * `ambulancia` - ambulancia * `bomberos` - bomberos
 * @export
 * @enum {string}
 */

export const RoleEnum = {
    Ciudadano: 'ciudadano',
    Policia: 'policia',
    Ambulancia: 'ambulancia',
    Bomberos: 'bomberos'
} as const;

export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];



