/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmergencyTypes model module.
 * @module models/EmergencyTypes
 * @version 1.0.0
 */
class EmergencyTypes {
    /**
     * Constructs a new <code>EmergencyTypes</code>.
     * @alias module:models/EmergencyTypes
     * @param name {String} 
     * @param icon {String} 
     * @param market {String} 
     */
    constructor(name, icon, market) { 
        
        EmergencyTypes.initialize(this, name, icon, market);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, icon, market) { 
        obj['name'] = name;
        obj['icon'] = icon;
        obj['market'] = market;
    }

    /**
     * Constructs a <code>EmergencyTypes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/EmergencyTypes} obj Optional instance to populate.
     * @return {module:models/EmergencyTypes} The populated <code>EmergencyTypes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmergencyTypes();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('market')) {
                obj['market'] = ApiClient.convertToType(data['market'], 'String');
            }
            if (data.hasOwnProperty('area_1')) {
                obj['area_1'] = ApiClient.convertToType(data['area_1'], 'Number');
            }
            if (data.hasOwnProperty('area_2')) {
                obj['area_2'] = ApiClient.convertToType(data['area_2'], 'Number');
            }
            if (data.hasOwnProperty('area_3')) {
                obj['area_3'] = ApiClient.convertToType(data['area_3'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmergencyTypes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmergencyTypes</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmergencyTypes.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['icon'] && !(typeof data['icon'] === 'string' || data['icon'] instanceof String)) {
            throw new Error("Expected the field `icon` to be a primitive type in the JSON string but got " + data['icon']);
        }
        // ensure the json data is a string
        if (data['market'] && !(typeof data['market'] === 'string' || data['market'] instanceof String)) {
            throw new Error("Expected the field `market` to be a primitive type in the JSON string but got " + data['market']);
        }

        return true;
    }


}

EmergencyTypes.RequiredProperties = ["name", "icon", "market"];

/**
 * @member {Number} id
 */
EmergencyTypes.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EmergencyTypes.prototype['name'] = undefined;

/**
 * @member {String} icon
 */
EmergencyTypes.prototype['icon'] = undefined;

/**
 * @member {String} market
 */
EmergencyTypes.prototype['market'] = undefined;

/**
 * @member {Number} area_1
 */
EmergencyTypes.prototype['area_1'] = undefined;

/**
 * @member {Number} area_2
 */
EmergencyTypes.prototype['area_2'] = undefined;

/**
 * @member {Number} area_3
 */
EmergencyTypes.prototype['area_3'] = undefined;






export default EmergencyTypes;

