/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FormTypeEnum.
* @enum {}
* @readonly
*/
export default class FormTypeEnum {
    
        /**
         * value: "FULL_FORM"
         * @const
         */
        "FULL_FORM" = "FULL_FORM";

    
        /**
         * value: "SMALL_FORM"
         * @const
         */
        "SMALL_FORM" = "SMALL_FORM";

    

    /**
    * Returns a <code>FormTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/FormTypeEnum} The enum <code>FormTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

