/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GCMDevice model module.
 * @module models/GCMDevice
 * @version 1.0.0
 */
class GCMDevice {
    /**
     * Constructs a new <code>GCMDevice</code>.
     * @alias module:models/GCMDevice
     * @param registrationId {String} 
     */
    constructor(registrationId) { 
        
        GCMDevice.initialize(this, registrationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, registrationId) { 
        obj['registration_id'] = registrationId;
    }

    /**
     * Constructs a <code>GCMDevice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/GCMDevice} obj Optional instance to populate.
     * @return {module:models/GCMDevice} The populated <code>GCMDevice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GCMDevice();

            if (data.hasOwnProperty('registration_id')) {
                obj['registration_id'] = ApiClient.convertToType(data['registration_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GCMDevice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GCMDevice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GCMDevice.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['registration_id'] && !(typeof data['registration_id'] === 'string' || data['registration_id'] instanceof String)) {
            throw new Error("Expected the field `registration_id` to be a primitive type in the JSON string but got " + data['registration_id']);
        }

        return true;
    }


}

GCMDevice.RequiredProperties = ["registration_id"];

/**
 * @member {String} registration_id
 */
GCMDevice.prototype['registration_id'] = undefined;






export default GCMDevice;

