/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GisFeatureEnum.
* @enum {}
* @readonly
*/
export default class GisFeatureEnum {
    
        /**
         * value: "Feature"
         * @const
         */
        "Feature" = "Feature";

    

    /**
    * Returns a <code>GisFeatureEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/GisFeatureEnum} The enum <code>GisFeatureEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

