/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GisFeatureCollectionEnum.
* @enum {}
* @readonly
*/
export default class GisFeatureCollectionEnum {
    
        /**
         * value: "FeatureCollection"
         * @const
         */
        "FeatureCollection" = "FeatureCollection";

    

    /**
    * Returns a <code>GisFeatureCollectionEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/GisFeatureCollectionEnum} The enum <code>GisFeatureCollectionEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

