/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LineMapGeometry model module.
 * @module models/LineMapGeometry
 * @version 1.0.0
 */
class LineMapGeometry {
    /**
     * Constructs a new <code>LineMapGeometry</code>.
     * @alias module:models/LineMapGeometry
     */
    constructor() { 
        
        LineMapGeometry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LineMapGeometry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/LineMapGeometry} obj Optional instance to populate.
     * @return {module:models/LineMapGeometry} The populated <code>LineMapGeometry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LineMapGeometry();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('coordinates')) {
                obj['coordinates'] = ApiClient.convertToType(data['coordinates'], [[['Number']]]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LineMapGeometry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LineMapGeometry</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['coordinates'])) {
            throw new Error("Expected the field `coordinates` to be an array in the JSON data but got " + data['coordinates']);
        }

        return true;
    }


}



/**
 * @member {module:models/LineMapGeometry.TypeEnum} type
 */
LineMapGeometry.prototype['type'] = undefined;

/**
 * @member {Array.<Array.<Array.<Number>>>} coordinates
 */
LineMapGeometry.prototype['coordinates'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
LineMapGeometry['TypeEnum'] = {

    /**
     * value: "MultiLineString"
     * @const
     */
    "MultiLineString": "MultiLineString"
};



export default LineMapGeometry;

