/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReadOnlyImages model module.
 * @module models/ReadOnlyImages
 * @version 1.0.0
 */
class ReadOnlyImages {
    /**
     * Constructs a new <code>ReadOnlyImages</code>.
     * @alias module:models/ReadOnlyImages
     */
    constructor() { 
        
        ReadOnlyImages.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReadOnlyImages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ReadOnlyImages} obj Optional instance to populate.
     * @return {module:models/ReadOnlyImages} The populated <code>ReadOnlyImages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReadOnlyImages();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('user_created')) {
                obj['user_created'] = ApiClient.convertToType(data['user_created'], 'String');
            }
            if (data.hasOwnProperty('thumbnail')) {
                obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'String');
            }
            if (data.hasOwnProperty('register_date')) {
                obj['register_date'] = ApiClient.convertToType(data['register_date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReadOnlyImages</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReadOnlyImages</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }
        // ensure the json data is a string
        if (data['user_created'] && !(typeof data['user_created'] === 'string' || data['user_created'] instanceof String)) {
            throw new Error("Expected the field `user_created` to be a primitive type in the JSON string but got " + data['user_created']);
        }
        // ensure the json data is a string
        if (data['thumbnail'] && !(typeof data['thumbnail'] === 'string' || data['thumbnail'] instanceof String)) {
            throw new Error("Expected the field `thumbnail` to be a primitive type in the JSON string but got " + data['thumbnail']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ReadOnlyImages.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ReadOnlyImages.prototype['name'] = undefined;

/**
 * @member {String} image
 */
ReadOnlyImages.prototype['image'] = undefined;

/**
 * @member {String} user_created
 */
ReadOnlyImages.prototype['user_created'] = undefined;

/**
 * @member {String} thumbnail
 */
ReadOnlyImages.prototype['thumbnail'] = undefined;

/**
 * @member {Date} register_date
 */
ReadOnlyImages.prototype['register_date'] = undefined;






export default ReadOnlyImages;

