/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ZoneMapProperties model module.
 * @module models/ZoneMapProperties
 * @version 1.0.0
 */
class ZoneMapProperties {
    /**
     * Constructs a new <code>ZoneMapProperties</code>.
     * @alias module:models/ZoneMapProperties
     */
    constructor() { 
        
        ZoneMapProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ZoneMapProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ZoneMapProperties} obj Optional instance to populate.
     * @return {module:models/ZoneMapProperties} The populated <code>ZoneMapProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ZoneMapProperties();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('begin')) {
                obj['begin'] = ApiClient.convertToType(data['begin'], 'Date');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Date');
            }
            if (data.hasOwnProperty('altitudeMode')) {
                obj['altitudeMode'] = ApiClient.convertToType(data['altitudeMode'], 'String');
            }
            if (data.hasOwnProperty('tessellate')) {
                obj['tessellate'] = ApiClient.convertToType(data['tessellate'], 'Number');
            }
            if (data.hasOwnProperty('extrude')) {
                obj['extrude'] = ApiClient.convertToType(data['extrude'], 'Number');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = ApiClient.convertToType(data['visibility'], 'Number');
            }
            if (data.hasOwnProperty('drawOrder')) {
                obj['drawOrder'] = ApiClient.convertToType(data['drawOrder'], 'Number');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('snippet')) {
                obj['snippet'] = ApiClient.convertToType(data['snippet'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('border_color')) {
                obj['border_color'] = ApiClient.convertToType(data['border_color'], 'String');
            }
            if (data.hasOwnProperty('background_color')) {
                obj['background_color'] = ApiClient.convertToType(data['background_color'], 'String');
            }
            if (data.hasOwnProperty('opacity')) {
                obj['opacity'] = ApiClient.convertToType(data['opacity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ZoneMapProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ZoneMapProperties</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['altitudeMode'] && !(typeof data['altitudeMode'] === 'string' || data['altitudeMode'] instanceof String)) {
            throw new Error("Expected the field `altitudeMode` to be a primitive type in the JSON string but got " + data['altitudeMode']);
        }
        // ensure the json data is a string
        if (data['icon'] && !(typeof data['icon'] === 'string' || data['icon'] instanceof String)) {
            throw new Error("Expected the field `icon` to be a primitive type in the JSON string but got " + data['icon']);
        }
        // ensure the json data is a string
        if (data['snippet'] && !(typeof data['snippet'] === 'string' || data['snippet'] instanceof String)) {
            throw new Error("Expected the field `snippet` to be a primitive type in the JSON string but got " + data['snippet']);
        }
        // ensure the json data is a string
        if (data['tag'] && !(typeof data['tag'] === 'string' || data['tag'] instanceof String)) {
            throw new Error("Expected the field `tag` to be a primitive type in the JSON string but got " + data['tag']);
        }
        // ensure the json data is a string
        if (data['border_color'] && !(typeof data['border_color'] === 'string' || data['border_color'] instanceof String)) {
            throw new Error("Expected the field `border_color` to be a primitive type in the JSON string but got " + data['border_color']);
        }
        // ensure the json data is a string
        if (data['background_color'] && !(typeof data['background_color'] === 'string' || data['background_color'] instanceof String)) {
            throw new Error("Expected the field `background_color` to be a primitive type in the JSON string but got " + data['background_color']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ZoneMapProperties.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ZoneMapProperties.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ZoneMapProperties.prototype['description'] = undefined;

/**
 * @member {Date} timestamp
 */
ZoneMapProperties.prototype['timestamp'] = undefined;

/**
 * @member {Date} begin
 */
ZoneMapProperties.prototype['begin'] = undefined;

/**
 * @member {Date} end
 */
ZoneMapProperties.prototype['end'] = undefined;

/**
 * @member {String} altitudeMode
 */
ZoneMapProperties.prototype['altitudeMode'] = undefined;

/**
 * @member {Number} tessellate
 */
ZoneMapProperties.prototype['tessellate'] = undefined;

/**
 * @member {Number} extrude
 */
ZoneMapProperties.prototype['extrude'] = undefined;

/**
 * @member {Number} visibility
 */
ZoneMapProperties.prototype['visibility'] = undefined;

/**
 * @member {Number} drawOrder
 */
ZoneMapProperties.prototype['drawOrder'] = undefined;

/**
 * @member {String} icon
 */
ZoneMapProperties.prototype['icon'] = undefined;

/**
 * @member {String} snippet
 */
ZoneMapProperties.prototype['snippet'] = undefined;

/**
 * @member {String} tag
 */
ZoneMapProperties.prototype['tag'] = undefined;

/**
 * @member {String} border_color
 */
ZoneMapProperties.prototype['border_color'] = undefined;

/**
 * @member {String} background_color
 */
ZoneMapProperties.prototype['background_color'] = undefined;

/**
 * Establece la opacidad entre 0 (transparente) y 1 (opaco).
 * @member {Number} opacity
 */
ZoneMapProperties.prototype['opacity'] = undefined;






export default ZoneMapProperties;

