/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GisFeatureEnum from './GisFeatureEnum';
import ZoneMapGeometry from './ZoneMapGeometry';
import ZoneMapProperties from './ZoneMapProperties';

/**
 * The ZoneMap model module.
 * @module models/ZoneMap
 * @version 1.0.0
 */
class ZoneMap {
    /**
     * Constructs a new <code>ZoneMap</code>.
     * A class to serialize locations as GeoJSON compatible data
     * @alias module:models/ZoneMap
     */
    constructor() { 
        
        ZoneMap.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ZoneMap</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ZoneMap} obj Optional instance to populate.
     * @return {module:models/ZoneMap} The populated <code>ZoneMap</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ZoneMap();

            if (data.hasOwnProperty('type')) {
                obj['type'] = GisFeatureEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('geometry')) {
                obj['geometry'] = ZoneMapGeometry.constructFromObject(data['geometry']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ZoneMapProperties.constructFromObject(data['properties']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ZoneMap</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ZoneMap</code>.
     */
    static validateJSON(data) {
        // validate the optional field `geometry`
        if (data['geometry']) { // data not null
          ZoneMapGeometry.validateJSON(data['geometry']);
        }
        // validate the optional field `properties`
        if (data['properties']) { // data not null
          ZoneMapProperties.validateJSON(data['properties']);
        }

        return true;
    }


}



/**
 * @member {module:models/GisFeatureEnum} type
 */
ZoneMap.prototype['type'] = undefined;

/**
 * @member {module:models/ZoneMapGeometry} geometry
 */
ZoneMap.prototype['geometry'] = undefined;

/**
 * @member {module:models/ZoneMapProperties} properties
 */
ZoneMap.prototype['properties'] = undefined;






export default ZoneMap;

