/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GisFeatureCollectionEnum from './GisFeatureCollectionEnum';
import ZoneMap from './ZoneMap';

/**
 * The ZoneMapList model module.
 * @module models/ZoneMapList
 * @version 1.0.0
 */
class ZoneMapList {
    /**
     * Constructs a new <code>ZoneMapList</code>.
     * @alias module:models/ZoneMapList
     */
    constructor() { 
        
        ZoneMapList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ZoneMapList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ZoneMapList} obj Optional instance to populate.
     * @return {module:models/ZoneMapList} The populated <code>ZoneMapList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ZoneMapList();

            if (data.hasOwnProperty('type')) {
                obj['type'] = GisFeatureCollectionEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], [ZoneMap]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ZoneMapList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ZoneMapList</code>.
     */
    static validateJSON(data) {
        if (data['features']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['features'])) {
                throw new Error("Expected the field `features` to be an array in the JSON data but got " + data['features']);
            }
            // validate the optional field `features` (array)
            for (const item of data['features']) {
                ZoneMap.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:models/GisFeatureCollectionEnum} type
 */
ZoneMapList.prototype['type'] = undefined;

/**
 * @member {Array.<module:models/ZoneMap>} features
 */
ZoneMapList.prototype['features'] = undefined;






export default ZoneMapList;

