/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsiApi);
  }
}(this, function(expect, AsiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsiApi.EmergencyTypes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmergencyTypes', function() {
    it('should create an instance of EmergencyTypes', function() {
      // uncomment below and update the code to test EmergencyTypes
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be.a(AsiApi.EmergencyTypes);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

    it('should have the property market (base name: "market")', function() {
      // uncomment below and update the code to test the property market
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

    it('should have the property area1 (base name: "area_1")', function() {
      // uncomment below and update the code to test the property area1
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

    it('should have the property area2 (base name: "area_2")', function() {
      // uncomment below and update the code to test the property area2
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

    it('should have the property area3 (base name: "area_3")', function() {
      // uncomment below and update the code to test the property area3
      //var instance = new AsiApi.EmergencyTypes();
      //expect(instance).to.be();
    });

  });

}));
