/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsiApi);
  }
}(this, function(expect, AsiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsiApi.Nested();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Nested', function() {
    it('should create an instance of Nested', function() {
      // uncomment below and update the code to test Nested
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be.a(AsiApi.Nested);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property projectName (base name: "project_name")', function() {
      // uncomment below and update the code to test the property projectName
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property alias (base name: "alias")', function() {
      // uncomment below and update the code to test the property alias
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "full_name")', function() {
      // uncomment below and update the code to test the property fullName
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property nit (base name: "nit")', function() {
      // uncomment below and update the code to test the property nit
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property logo (base name: "logo")', function() {
      // uncomment below and update the code to test the property logo
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property publicBackground (base name: "public_background")', function() {
      // uncomment below and update the code to test the property publicBackground
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property sidebarBackground (base name: "sidebar_background")', function() {
      // uncomment below and update the code to test the property sidebarBackground
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property background (base name: "background")', function() {
      // uncomment below and update the code to test the property background
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property wikiIcon (base name: "wiki_icon")', function() {
      // uncomment below and update the code to test the property wikiIcon
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property wikiTitle (base name: "wiki_title")', function() {
      // uncomment below and update the code to test the property wikiTitle
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property formType (base name: "form_type")', function() {
      // uncomment below and update the code to test the property formType
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property publicTitleForm (base name: "public_title_form")', function() {
      // uncomment below and update the code to test the property publicTitleForm
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property eventName (base name: "event_name")', function() {
      // uncomment below and update the code to test the property eventName
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property categoryLabel (base name: "category_label")', function() {
      // uncomment below and update the code to test the property categoryLabel
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property requiredEmergencyControlPoint (base name: "required_emergency_control_point")', function() {
      // uncomment below and update the code to test the property requiredEmergencyControlPoint
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property allowCreateEmergenciesByWeb (base name: "allow_create_emergencies_by_web")', function() {
      // uncomment below and update the code to test the property allowCreateEmergenciesByWeb
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property extraEmergencyCategories (base name: "extra_emergency_categories")', function() {
      // uncomment below and update the code to test the property extraEmergencyCategories
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property zone (base name: "zone")', function() {
      // uncomment below and update the code to test the property zone
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property emergenciesAllowed (base name: "emergencies_allowed")', function() {
      // uncomment below and update the code to test the property emergenciesAllowed
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property extraZones (base name: "extra_zones")', function() {
      // uncomment below and update the code to test the property extraZones
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property extraPoints (base name: "extra_points")', function() {
      // uncomment below and update the code to test the property extraPoints
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

    it('should have the property extraLines (base name: "extra_lines")', function() {
      // uncomment below and update the code to test the property extraLines
      //var instance = new AsiApi.Nested();
      //expect(instance).to.be();
    });

  });

}));
