/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsiApi);
  }
}(this, function(expect, AsiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsiApi.PatchedEmergency();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PatchedEmergency', function() {
    it('should create an instance of PatchedEmergency', function() {
      // uncomment below and update the code to test PatchedEmergency
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be.a(AsiApi.PatchedEmergency);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "start_time")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property finishTime (base name: "finish_time")', function() {
      // uncomment below and update the code to test the property finishTime
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property registerDate (base name: "register_date")', function() {
      // uncomment below and update the code to test the property registerDate
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property emergencyType (base name: "emergency_type")', function() {
      // uncomment below and update the code to test the property emergencyType
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property userCreatedId (base name: "user_created_id")', function() {
      // uncomment below and update the code to test the property userCreatedId
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property controlPoint (base name: "control_point")', function() {
      // uncomment below and update the code to test the property controlPoint
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property extraCategory (base name: "extra_category")', function() {
      // uncomment below and update the code to test the property extraCategory
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

    it('should have the property avatarUrl (base name: "avatar_url")', function() {
      // uncomment below and update the code to test the property avatarUrl
      //var instance = new AsiApi.PatchedEmergency();
      //expect(instance).to.be();
    });

  });

}));
