/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Device from '../models/Device';

/**
* Devices2 service.
* @module api/Devices2Api
* @version 1.0.0
*/
export default class Devices2Api {

    /**
    * Constructs a new Devices2Api. 
    * @alias module:api/Devices2Api
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the notifications2DeviceCreate operation.
     * @callback module:api/Devices2Api~notifications2DeviceCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Registra un dispositivo android recibir las notificaciones push
     * Registra un dispositivo android para recibir las notificaciones push
     * @param {module:models/Device} device 
     * @param {module:api/Devices2Api~notifications2DeviceCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    notifications2DeviceCreate(device, callback) {
      let postBody = device;
      // verify the required parameter 'device' is set
      if (device === undefined || device === null) {
        throw new Error("Missing the required parameter 'device' when calling notifications2DeviceCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jwtAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/notifications2/device/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the notifications2UnlinkDeviceCreate operation.
     * @callback module:api/Devices2Api~notifications2UnlinkDeviceCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Elimina un dispositivo android para recibir las notificaciones push
     * Elimina un dispositivo android para recibir las notificaciones push
     * @param {module:models/Device} device 
     * @param {module:api/Devices2Api~notifications2UnlinkDeviceCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    notifications2UnlinkDeviceCreate(device, callback) {
      let postBody = device;
      // verify the required parameter 'device' is set
      if (device === undefined || device === null) {
        throw new Error("Missing the required parameter 'device' when calling notifications2UnlinkDeviceCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jwtAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/notifications2/unlink-device/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
