/**
 * ASI API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LineMap from '../models/LineMap';
import LineMapList from '../models/LineMapList';

/**
* LineMaps service.
* @module api/LineMapsApi
* @version 1.0.0
*/
export default class LineMapsApi {

    /**
    * Constructs a new LineMapsApi. 
    * @alias module:api/LineMapsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the mapsLinesList operation.
     * @callback module:api/LineMapsApi~mapsLinesListCallback
     * @param {String} error Error message, if any.
     * @param {module:models/LineMapList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * text
     * @param {Object} opts Optional parameters
     * @param {Number} [companyId] Filter lines by company id
     * @param {module:api/LineMapsApi~mapsLinesListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/LineMapList}
     */
    mapsLinesList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'company_id': opts['companyId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jwtAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LineMapList;
      return this.apiClient.callApi(
        '/api/maps/lines/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the mapsLinesRetrieve operation.
     * @callback module:api/LineMapsApi~mapsLinesRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:models/LineMap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this line map.
     * @param {module:api/LineMapsApi~mapsLinesRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/LineMap}
     */
    mapsLinesRetrieve(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling mapsLinesRetrieve");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jwtAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LineMap;
      return this.apiClient.callApi(
        '/api/maps/lines/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
