/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EmergencyRoleSerializerRequest } from '../models';
// @ts-ignore
import type { User } from '../models';
/**
 * ChangeRoleApi - axios parameter creator
 * @export
 */
export const ChangeRoleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Crear una solicitud de cambio de rol
         * @summary Solicitud de cambio de rol
         * @param {EmergencyRoleSerializerRequest} emergencyRoleSerializerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mainUsersChangeRoleCreate: async (emergencyRoleSerializerRequest: EmergencyRoleSerializerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emergencyRoleSerializerRequest' is not null or undefined
            assertParamExists('mainUsersChangeRoleCreate', 'emergencyRoleSerializerRequest', emergencyRoleSerializerRequest)
            const localVarPath = `/api/main/users/change-role/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emergencyRoleSerializerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChangeRoleApi - functional programming interface
 * @export
 */
export const ChangeRoleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChangeRoleApiAxiosParamCreator(configuration)
    return {
        /**
         * Crear una solicitud de cambio de rol
         * @summary Solicitud de cambio de rol
         * @param {EmergencyRoleSerializerRequest} emergencyRoleSerializerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mainUsersChangeRoleCreate(emergencyRoleSerializerRequest: EmergencyRoleSerializerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mainUsersChangeRoleCreate(emergencyRoleSerializerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChangeRoleApi.mainUsersChangeRoleCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChangeRoleApi - factory interface
 * @export
 */
export const ChangeRoleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChangeRoleApiFp(configuration)
    return {
        /**
         * Crear una solicitud de cambio de rol
         * @summary Solicitud de cambio de rol
         * @param {ChangeRoleApiMainUsersChangeRoleCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mainUsersChangeRoleCreate(requestParameters: ChangeRoleApiMainUsersChangeRoleCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.mainUsersChangeRoleCreate(requestParameters.emergencyRoleSerializerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for mainUsersChangeRoleCreate operation in ChangeRoleApi.
 * @export
 * @interface ChangeRoleApiMainUsersChangeRoleCreateRequest
 */
export interface ChangeRoleApiMainUsersChangeRoleCreateRequest {
    /**
     * 
     * @type {EmergencyRoleSerializerRequest}
     * @memberof ChangeRoleApiMainUsersChangeRoleCreate
     */
    readonly emergencyRoleSerializerRequest: EmergencyRoleSerializerRequest
}

/**
 * ChangeRoleApi - object-oriented interface
 * @export
 * @class ChangeRoleApi
 * @extends {BaseAPI}
 */
export class ChangeRoleApi extends BaseAPI {
    /**
     * Crear una solicitud de cambio de rol
     * @summary Solicitud de cambio de rol
     * @param {ChangeRoleApiMainUsersChangeRoleCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChangeRoleApi
     */
    public mainUsersChangeRoleCreate(requestParameters: ChangeRoleApiMainUsersChangeRoleCreateRequest, options?: RawAxiosRequestConfig) {
        return ChangeRoleApiFp(this.configuration).mainUsersChangeRoleCreate(requestParameters.emergencyRoleSerializerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

